- Makefile
- README.md
- ci/azure-pipelines.yml
- ci/version_var.sh
- cmd/edv-rest/go.mod
- cmd/edv-rest/startcmd/start.go
- images/edv-rest/Dockerfile
Closes #14 
A Docker image for an EDV server can now be published.
Added a line of output to indicate the server is running.
Fixed the readme file not rendering correctly.
> feat: EDV Docker Image

- cmd/edv-rest/startcmd/start.go
- cmd/edv-rest/startcmd/start_test.go
- pkg/client/edv/client.go
- pkg/client/edv/client_test.go
- pkg/restapi/edv/operation/operations.go
- pkg/restapi/edv/operation/operations_test.go
- pkg/utils/cmd/util.go
- pkg/utils/cmd/util_test.go
- test/bdd/features/edv_e2e_api.feature
- test/bdd/pkg/edv/edv_steps.go
closes #20
Fixed an issue that was preventing URL-encoded slashes from being used in IDs.
Made some adjustments to returned error codes and function names to improve spec compliance.
Did some minor refactoring and formatting.
> fix: Allow URL-encoded slashes in IDs

- README.md
- cmd/edv-rest/go.mod
- cmd/edv-rest/go.sum
- docs/rest/edv_cli.md
- docs/rest/edv_docker.md
- docs/test/build.md
- go.mod
- go.sum
- test/bdd/go.sum
closes #23
Added documentation for 0.1.1 release
Updated edge-core dependency to 0.1.1
> docs: 0.1.1 Documentation

- pkg/client/edv/client.go
- pkg/client/edv/client_test.go
- test/bdd/pkg/context/context.go
- test/bdd/pkg/edv/edv_steps.go
- Also some minor refactoring in the client unit tests.
> refactor: Client now directly returns EncryptedDocument instead of bytes

- images/edv-rest/Dockerfile
Go's netgo implementation currently does not respect hostname overrides defined in /etc/hosts if the /etc/nsswitch.conf does not exists.
Made changes to your Dockerfile to add a standard /etc/nsswitch.conf to fix this issue.
> fix: Added nsswitch.conf into the docker image

- pkg/edvutils/edvutils.go
- pkg/edvutils/edvutils_test.go
Added a function which can be used by other packages to generate an EDV compatible ID.
> feat: Generate EDV compatible ID function

- cmd/edv-rest/go.mod
- cmd/edv-rest/go.sum
- go.mod
- go.sum
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go
- test/bdd/go.mod
- test/bdd/go.sum
Fixes an issue where encrypted index querying with a CouchDB backend would fail in some cases. The issue is that the CouchDB query call was only returning the first 25 matching documents. By using the updated edge-core implementation, now the remaining matching documents are retrieved via pagination.
closes #70
> fix: CouchDB query missing results

- cmd/edv-rest/startcmd/start.go
- cmd/edv-rest/startcmd/start_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/restapi/messages/messages.go
- pkg/restapi/models/models.go
- pkg/restapi/operation/operations.go
- pkg/restapi/operation/operations_test.go
- pkg/restapi/operation/respond.go
- pkg/restapi/operation/utils.go
- This adds an implementation of a batch endpoint extension. In this commit, it's very inefficient since it doesn't actually batch calls to the underlying database provider. It will be optimized in another commit.
- Also added more information to the startup log message.
> feat: Initial batch endpoint extension implementation

- cmd/edv-rest/go.mod
- cmd/edv-rest/go.sum
- cmd/edv-rest/startcmd/start.go
- go.mod
- go.sum
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go
- test/bdd/go.mod
- test/bdd/go.sum
Encrypted index querying when using CouchDB is now much faster. Calls to CouchDB that used to be done one at a time are now done in bulk. The performance difference is especially large when there are many documents that share the same encrypted index name tags.
> feat: Query with CouchDB backend performance optimization

- cmd/edv-rest/startcmd/start_test.go
- pkg/client/client_test.go
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go
- pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go
- pkg/edvprovider/edvprovider.go
- pkg/edvprovider/memedvprovider/memedvprovider.go
- pkg/restapi/operation/operations.go
- pkg/restapi/operation/operations_test.go
Document upserts are now batched together and put in CouchDB in bulk. Batch endpoint is now much faster when using CouchDB.
> feat: Batch performance optimization with CouchDB backend

- pkg/auth/zcapld/service.go
Signed-off-by: George Aristy <george.aristy@securekey.com>
> fix: zcaps middlware: wrong doc contents cached

- test/bdd/mock/loginconsent/main.go
> chore: Lower TLS min version to 12 in mock login consent

- cmd/edv-rest/go.mod
- cmd/edv-rest/go.sum
- go.mod
- go.sum
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/mock/loginconsent/go.mod
- test/bdd/mock/loginconsent/go.sum
includes fix of Ed25519 KID value in KMS and JWE recipient integrity checks (APU/APV and multirecipient AAD)
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
> chore: latest aries-framework-go

- pkg/restapi/operation/operations.go
- pkg/restapi/operation/operations_test.go
The batch endpoint no longer considers an operation that tries to delete a non-existent document to be an error. The returned response message will still indicate that it couldn't be found, but the status code will be 200 and subsequent operations after the delete will still attempt to execute.
> feat: Batch endpoint no longer gives up when deleting a non-existent doc

- test/bdd/bddtests_test.go
- test/bdd/features/edv_e2e_api.feature
- test/bdd/features/healthcheck_api.feature
- test/bdd/fixtures/edv-rest/.env
- test/bdd/fixtures/edv-rest/docker-compose.yml
- test/bdd/fixtures/edv-rest/nginx-config/nginx.conf
- test/bdd/pkg/context/context.go
- test/bdd/pkg/edv/edv_steps.go
- test/bdd/pkg/interop/edv_interop_steps.go
- BDD tests now use a load balancer in front of two EDV servers.
- Added a new test that tests parallel document creation.
- Reduced the BDD test delay from 50 to 25 (it was way longer than necessary).
> test: Demonstrate load-balancing in BDD-tests

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/edvprovider/edvprovider.go
- pkg/edvprovider/edvprovider_test.go
- pkg/restapi/messages/messages.go
- pkg/restapi/models/models.go
- pkg/restapi/operation/operations.go
- pkg/restapi/operation/operations_test.go
- test/bdd/features/edv_e2e_api.feature
- test/bdd/pkg/edv/edv_steps.go
- Added a method to the EDV client for asking an EDV server to add indexes.
- Added a BDD test step for adding an index using the client.
- Added log message to server when receiving a request to add indexes.
- Changed "attribute key" to "attribute name" to keep in line with current  draft PR in EDV spec for the "add index" endpoint.
> feat: Add index method for EDV client and BDD test

- cmd/edv-rest/go.mod
- cmd/edv-rest/go.sum
- cmd/edv-rest/startcmd/start.go
- cmd/edv-rest/startcmd/start_test.go
- go.mod
- go.sum
- pkg/client/client_test.go
- pkg/edvprovider/edvprovider.go
- pkg/edvprovider/edvprovider_test.go
- pkg/edvutils/edvutils.go
- pkg/edvutils/edvutils_test.go
- pkg/restapi/controller_test.go
- pkg/restapi/models/models.go
- pkg/restapi/operation/operations.go
- pkg/restapi/operation/operations_test.go
- pkg/restapi/operation/respond.go
- test/bdd/go.mod
- test/bdd/go.sum
Previously, a new database/collection was created for every vault. This could cause issues when there are many vaults as the number of databases can start to become unmanageable. This change uses a single database for all documents.
> feat: Use one database for all documents instead of one per vault

- cmd/edv-rest/startcmd/start.go
- cmd/edv-rest/startcmd/start_test.go
- docs/rest/edv_cli.md
- scripts/check_integration.sh
- test/bdd/pkg/context/context.go
- test/bdd/pkg/edv/edv_steps.go
Now GNAP and ZCAP authorization can run at the same time. The way this implementation works is that if the server has both mechanisms active, then a client may choose to authorize themselves with either one, (rather than the two stacking on top of each other).
> feat: Allow GNAP and ZCAP authorization to work at the same time

- Makefile
- README.md
* Resolved a warning from Docker that would get printed when running the generate-test-keys Makefile target on an arm64 system. The warning from Docker alerts you that the image for frapsoft/openssl is for amd64, which doesn't match the system you're on (when using an arm64-based OS). To resolve the warning, you have to either use an image that matches the system architecture, or explicitly state the platform using the --platform flag. In this case, there is only an amd64 version of frapsoft/openssl, so I added the explicit flag to resolve the warning. I also added a TODO for us to find an arm64 alternative in the future (although the amd64 version of frapsoft/openssl does seem to work fine on arm64 Mac OS currently, presumably due to Apple's Rosetta translation layer or some other …
> fix: Docker warning and update spec links

- test/bdd/bddtests_test.go
- test/bdd/fixtures/edv-rest/.env
- test/bdd/pkg/context/context.go
Signed-off-by: Yevgen Pukhta <eugene.pukhta@gmail.com>
Changes:
- pump auth to the latest (https://github.com/orgs/trustbloc-cicd/packages/container/auth/42687299?tag=0.1.9-snapshot-4b6c339)
- fix edv bdd tests to work with the latest auth
- fix for `DISABLE_COMPOSITION` mode. BDD context was not initialized when the flag had been set.
> chore(deps): bump auth to 0.1.9-snapshot-4b6c339
