trustbloc/edv

pkg/client/edv/client.go, pkg/client/edv/client_test.go, pkg/restapi/edv/operation/models.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go
closes #3 
Added an EDV client which can be used to communicate with an EDV server.
Also fixed some spec compliance issues in the existing EDV server implementation.
=> feat: EDV Client

Makefile
Corrected the docker image tag.
=> fix: Docker image tag correction

README.md, docs/rest/edv_cli.md
=> docs: 0.1.1 Documentation fix

ci/version_var.sh
=> chore: Complete release 0.1.1

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start.go, docs/rest/edv_cli.md, docs/rest/edv_docker.md, go.mod, go.sum, test/bdd/go.sum
- Added documentation for 0.1.2 release
- Updated commands so that they also print out the names of the environment variables
- Updated edge-core dependency to 0.1.2
=> docs: 0.1.2 Documentation

ci/version_var.sh
=> chore: Release 0.1.2

ci/version_var.sh
=> chore: Complete release 0.1.2

pkg/client/edv/client.go, pkg/client/edv/client_test.go, test/bdd/features/edv_e2e_api.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go
=> feat: Client now supports query endpoint

pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go
=> feat: Unique encrypted index+value pair support

cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start.go, go.mod, go.sum, pkg/client/edv/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/restapi/edv/controller.go, pkg/restapi/edv/controller_test.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go, test/bdd/go.sum
=> chore: Add couchdb prefix

pkg/client/edv/client.go, pkg/client/edv/client_test.go, pkg/restapi/edv/controller_test.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/features/edv_e2e_api.feature, test/bdd/features/edv_interop_transmute.feature, test/bdd/go.mod, test/bdd/pkg/common/common.go, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go, test/bdd/pkg/interop/edv_interop_steps.go
=> test: Interop with Transmute

ci/version_var.sh, cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start.go, docs/rest/edv_cli.md, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Release 0.1.3

ci/version_var.sh
=> chore: Complete release 0.1.3

ci/azure-pipelines.yml, ci/version_var.sh
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> ci: publish snapshots to external repo

pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go
=> fix: Unit test compatibility with CI

.golangci.yml, cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, cmd/edv-rest/main.go, cmd/edv-rest/startcmd/start.go, go.mod, go.sum, pkg/client/edv/client.go, pkg/client/edv/client_test.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go, test/bdd/dockerutil/compose.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: Switch logging to edge-core package

cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go
=> feat: Set log level via command line flag

cmd/edv-rest/startcmd/start.go, pkg/restapi/edv/controller_test.go, pkg/restapi/edv/models/models.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go
=> feat: Endpoint for changing logging level on the fly

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, pkg/restapi/edv/controller_test.go, pkg/restapi/edv/operation/operations.go, pkg/restapi/edv/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: Endpoint for getting all currently set log levels

cmd/edv-rest/main.go, cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go, pkg/client/client.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/restapi/messages/messages.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, pkg/restapi/operation/utils.go
=> feat: Extensive logging

pkg/restapi/operation/operations_test.go
=> test: Remove invalid unit tests

cmd/edv-rest/main.go, cmd/edv-rest/startcmd/start.go, pkg/client/client.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, test/bdd/dockerutil/compose.go
=> refactor: Made log module names lowercase

cmd/edv-rest/startcmd/start.go
It was not displaying correctly.
=> fix: Corrected the "invalid logging level" log message

cmd/edv-rest/startcmd/start.go, test/bdd/fixtures/edv-rest/docker-compose.yml
=> feat: Add prefix to log-level env var

pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> fix: Missing error check when creating store

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start_test.go, go.mod, go.sum, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/restapi/operation/operations.go, test/bdd/go.mod, test/bdd/go.sum
- Update edge-core dependency (includes trustbloc/edge-core#52, trustbloc/edge-core#55)
=> chore: update edge-core dependency

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, pkg/client/client.go, pkg/client/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider_test.go, pkg/restapi/controller_test.go, pkg/restapi/messages/messages.go, pkg/restapi/operation/openapi.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: Endpoint for retrieving all documents in a vault

pkg/restapi/operation/operations_test.go
=> fix: intermittently failing unit test

pkg/restapi/healthcheck/operation/operations.go, test/bdd/go.mod, test/bdd/pkg/common/common_steps.go
=> refactor: Replace logrus with edge-core logging in health check code

ci/version_var.sh
=> chore: Complete release 0.1.4

Makefile, ci/azure-pipelines.yml, cmd/edv-rest/go.mod, cmd/edv-rest/startcmd/start_test.go, docs/test/build.md, go.mod, pkg/client/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, test/bdd/go.mod
=> chore: Update to Go 1.15

cmd/edv-rest/main.go, cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go, pkg/client/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider_test.go, pkg/edvutils/edvutils.go, pkg/edvutils/edvutils_test.go, pkg/restapi/messages/messages.go, pkg/restapi/models/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, pkg/restapi/operation/utils.go, test/bdd/bddtests_test.go, test/bdd/features/edv_e2e_api.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go, test/bdd/pkg/interop/edv_interop_steps.go
=> feat: EDV server generates uuid names during creation

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start.go, go.mod, go.sum, test/bdd/fixtures/couchdb/.env, test/bdd/fixtures/couchdb/couchdb-config/config.ini, test/bdd/fixtures/couchdb/docker-compose.yml, test/bdd/fixtures/edv-rest/.env, test/bdd/go.mod, test/bdd/go.sum
Signed-off-by: Grace Liu <grace.liu@securekey.com>
=> chore: update couchdb to v3.1.0

pkg/client/client.go, pkg/client/client_test.go, pkg/restapi/controller_test.go, pkg/restapi/operation/operations.go
Updated the query endpoint per https://github.com/decentralized-identity/secure-data-store/issues/110.
=> feat: Update query endpoint

pkg/client/client_test.go, pkg/edvutils/edvutils.go, pkg/edvutils/edvutils_test.go, pkg/restapi/messages/messages.go, pkg/restapi/models/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, test/bdd/pkg/edv/edv_steps.go, test/bdd/pkg/interop/edv_interop_steps.go
Closes: #6 
New PR after accidentally closing PR #126 
Signed-off-by: Grace Liu <grace.liu@securekey.com>
=> feat: incoming request validation

cmd/edv-rest/startcmd/start_test.go, pkg/client/client.go, pkg/client/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider_test.go, pkg/restapi/controller_test.go, pkg/restapi/messages/messages.go, pkg/restapi/operation/openapi.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, test/bdd/features/edv_e2e_api.feature, test/bdd/features/edv_interop_transmute.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go, test/bdd/pkg/interop/edv_interop_steps.go
part of: #9 
Signed-off-by: Grace Liu <grace.liu@securekey.com>
=> feat: update document api

pkg/client/client.go, pkg/client/client_test.go, pkg/restapi/operation/operations.go, test/bdd/bddtests_test.go, test/bdd/features/edv_e2e_api.feature, test/bdd/fixtures/auth-rest/.env, test/bdd/fixtures/auth-rest/docker-compose.yml, test/bdd/fixtures/oathkeeper/config.yaml, test/bdd/fixtures/oathkeeper/rules/resource-server.json, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go
=> test: Add oathkeeper to bdd test

pkg/client/client.go
Signed-off-by: Grace Liu <grace.liu@securekey.com>
=> fix: Remove incorrect client delete document status code check

pkg/client/client.go, pkg/client/client_test.go, test/bdd/pkg/edv/edv_steps.go
=> refactor: edv client and add HeadersOpt optional function

cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go, pkg/auth/zcapld/service.go, pkg/auth/zcapld/service_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/restapi/controller.go, pkg/restapi/controller_test.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/features/edv_e2e_api.feature, test/bdd/fixtures/oathkeeper/rules/resource-server.json, test/bdd/go.mod, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go, test/bdd/pkg/interop/edv_interop_steps.go
=> feat: Add zcap verify

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update aries resvision

test/bdd/pkg/edv/edv_steps.go
=> fix: chain capability signer

cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go, pkg/auth/zcapld/service.go, pkg/auth/zcapld/service_test.go, test/bdd/pkg/context/context.go
=> fix: change expected action to write

cmd/edv-rest/startcmd/start.go
=> fix: Allow DELETE method in CORS options

cmd/edv-rest/startcmd/start.go
=> fix: add MethodOptions to cors

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, pkg/auth/zcapld/context.go, pkg/auth/zcapld/service.go
=> fix: add caching document loader for zcap

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update edge-core revision

cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go, pkg/client/client.go, pkg/client/client_test.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go, pkg/edvprovider/memedvprovider/memedvprovider.go, pkg/restapi/controller_test.go, pkg/restapi/messages/messages.go, pkg/restapi/models/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go, pkg/restapi/operation/utils.go, test/bdd/pkg/edv/edv_steps.go
=> feat: Option to allow query endpoint to return full document contents

cmd/edv-rest/startcmd/start.go, cmd/edv-rest/startcmd/start_test.go
=> feat: add cors flag to enable it

pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/restapi/messages/messages.go, pkg/restapi/operation/operations_test.go, pkg/restapi/operation/respond.go
=> fix: Incorrect response when query finds no matching documents

pkg/auth/zcapld/service.go
The aries framework and json-gold libraries are adding documents to the `CachingDocumentLoader` while processing json-ld documents. This risks concurrent read/write of `CachingDocumentLoader`, which is backed by a regular map.
We work around this by creating a new `CachingDocumentLoader` for every verification. Documents are loaded once.
Signed-off-by: George Aristy <george.aristy@securekey.com>
=> fix: ZCAP middleware panic

README.md, cmd/edv-rest/startcmd/start.go, docs/extensions.md, docs/rest/edv_cli.md
=> docs: Updated documentation

ci/version_var.sh, cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Release v0.1.5

ci/version_var.sh
=> chore: Complete v0.1.5 release

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, docs/rest/edv_docker.md, test/bdd/fixtures/edv-rest/.env
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> ci: migrate to ghcr

ci/azure-pipelines.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> fix: use ghcr for docker login

images/edv-rest/Dockerfile
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: add docker label for github repo

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, pkg/auth/zcapld/context.go, pkg/auth/zcapld/service.go, test/bdd/go.mod, test/bdd/go.sum
This PR adds support for context caching for LD document loader. It sheds another 1.5-2 sec off the onboarding routine.
Part of https://github.com/trustbloc/kms/issues/146
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> perf: improve performance of ZCAP capability creation

pkg/edvprovider/couchdbedvprovider/couchdbedvprovider.go, pkg/edvprovider/couchdbedvprovider/couchdbedvprovider_test.go, pkg/edvprovider/edvprovider.go, pkg/restapi/models/models.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go
=> feat: Querying with the "has" keyword

pkg/client/client.go, pkg/client/client_test.go
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>
=> feat: Adds WithHTTPClient option for the client.

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum, test/bdd/mock/loginconsent/go.mod, test/bdd/mock/loginconsent/go.sum
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>
=> chore: Updates edge-core revision

pkg/auth/zcapld/service.go
Signed-off-by: George Aristy <george.aristy@securekey.com>
=> chore: zcap authz - support verification of JsonWebSignature2020

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum
=> chore: Update aries-framework-go-ext commit version

ci/version_var.sh
=> chore: Complete v0.1.6 release

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, cmd/edv-rest/startcmd/start.go, go.mod, go.sum
=> fix: EDV panic - index out of range

cmd/edv-rest/go.mod, cmd/edv-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
=> chore: update afgo

ci/version_var.sh
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
=> chore: complete release

.github/workflows/build.yml
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
=> fix: ci name

pkg/edvprovider/edvprovider.go, pkg/edvprovider/edvprovider_test.go, pkg/restapi/controller_test.go, pkg/restapi/messages/messages.go, pkg/restapi/models/models.go, pkg/restapi/operation/openapi.go, pkg/restapi/operation/operations.go, pkg/restapi/operation/operations_test.go, test/bdd/pkg/edv/edv_steps.go
Also removed some unused code.
=> feat: Add index endpoint

cmd/edv-rest/startcmd/start.go
Signed-off-by: Andrii Holovko <andriy.holovko@gmail.com>
=> fix: cors for gnap

cmd/edv-rest/startcmd/start_test.go
=> test: Add GNAP unit tests

cmd/edv-rest/startcmd/start_test.go, scripts/check_integration.sh, test/bdd/pkg/context/context.go, test/bdd/pkg/edv/edv_steps.go
=> test: Unit and BDD tests for simultaneous GNAP+ZCAP support

.github/workflows/build.yml
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
=> ci: add semantic commit check
